# Generated by Django 6.1.1 on 2026-09-09 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('rival', models.CharField(max_length=100)),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
