# Generated by Django 6.1.1 on 2026-09-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TITULAR', 'Titular'), ('SUPLENTE', 'Suplente')], default='TITULAR', max_length=20)),
                ('posicion_cancha', models.CharField(blank=True, help_text='Ej: Lateral derecho, Mediocampista ofensivo, etc.', max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='partidos.partido')),
            ],
            options={
                'verbose_name': 'Alineación',
                'verbose_name_plural': 'Alineaciones',
                'ordering': ['partido', 'tipo', 'orden'],
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
