# Generated by Django 6.1.1 on 2026-09-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='equipos.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
