# Generated by Django 6.1.1 on 2026-09-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(blank=True, help_text='Se completa automáticamente. Sirve para conservar el historial si se borra el jugador.', max_length=200)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tiempo_jugado', models.CharField(choices=[('COMPLETO', 'Partido completo'), ('SALIO_2DO', 'Salió en el segundo tiempo'), ('ENTRO_2DO', 'Entró en el segundo tiempo'), ('POCO', 'Jugó pocos minutos'), ('NO_JUGO', 'No ingresó')], default='COMPLETO', max_length=20)),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadisticas', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='partidos.partido')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['partido', 'nombre_jugador'],
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
