# Generated by Django 6.1.1 on 2026-09-21 22:54

import django.db.models.deletion
import equipos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('color_primario', models.CharField(default='#1a73e8', max_length=7)),
                ('color_secundario', models.CharField(default='#34a853', max_length=7)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=equipos.models.generar_codigo_invitacion, max_length=10, unique=True)),
                ('rol_asignado', models.CharField(choices=[('DT', 'Director Técnico'), ('AYUDANTE', 'Ayudante de Campo'), ('JUGADOR', 'Jugador')], default='JUGADOR', max_length=20)),
                ('usos_maximos', models.PositiveIntegerField(default=0, help_text='0 = ilimitado')),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('expira', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DT', 'Director Técnico'), ('AYUDANTE', 'Ayudante de Campo'), ('JUGADOR', 'Jugador')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='equipos.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['equipo', 'rol', 'usuario__username'],
                'unique_together': {('usuario', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje opcional para el DT', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='equipos.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ingreso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de ingreso',
                'verbose_name_plural': 'Solicitudes de ingreso',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('equipo', 'usuario')},
            },
        ),
    ]
