# Generated by Django 6.1.1 on 2026-09-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'No voy'), ('DUDA', 'Duda')], default='DUDA', max_length=20)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='jugadores.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='partidos.partido')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['partido', 'jugador__apellido'],
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
